SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPAWN_RATE = 0.8  # seconds

PLAYER_RADIUS = 20
PLAYER_TURN_ACCELERATION = 800
PLAYER_MAX_TURN_SPEED = 400
PLAYER_TURN_DRAG = 0.92
PLAYER_ACCELERATION = 300
PLAYER_MAX_SPEED = 500
PLAYER_DRAG = 0.95

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3 #seconds

SHOT_RADIUS = 5

PLAYER_LIVES = 3
RESPAWN_TIME = 2.0  # seconds